### ISSUE TITLE
Haversine

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pytolemy#1]
@gigly222 We need the great arc distance, no matter what the ultimate vision for the project ends up being. 

* [ ] Create a file, `spatial.py`, in `utils/`
* [ ] Write the func there, and create tests in the `test/` dir

Please make sure to create a branch off of `develop` and then submit a PR when you think you've got the answer.

**Comment by tgsmith61591** [comment]
Closing since this was handled by #2 and closed in e3f078e

**Comment by gigly222** [comment]
Kinda fun to get closed messages
